<a href="https://colab.research.google.com/github/be-next/TP-IA/blob/main/calcul_matriciel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Calcul matriciel avec NumPy

In [1]:
import numpy as np

## Déclaration d'un matrice 3 x 2

In [2]:
A = np.array([[1, 2], [3, 4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
A.shape

(3, 2)

## Transposé d'une matrice

Soit une matrice $( A )$ de dimension $( 3 \times 2 )$ :
$$
A = \begin{pmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22} \\
a_{31} & a_{32}
\end{pmatrix}
$$

La transposée de $( A )$, notée $( A^T )$, est une matrice de dimension $( 2 \times 3 )$ et est donnée par :
$$
A^T = \begin{pmatrix}
a_{11} & a_{21} & a_{31} \\
a_{12} & a_{22} & a_{32}
\end{pmatrix}
$$

In [5]:
B = A.T
B

array([[1, 3, 5],
       [2, 4, 6]])

In [6]:
B.shape

(2, 3)

## Addition de matrices

Pour être additionnées, les matrices doivent être de même dimension.

Soient deux matrices carrées $A$ et $B$ de dimension $2 \times 2$ :
$$
A = \begin{pmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{pmatrix}, \quad
B = \begin{pmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22}
\end{pmatrix}
$$

L'addition de $A$ et $B$ est donnée par :
$$
A + B = \begin{pmatrix}
a_{11} + b_{11} & a_{12} + b_{12} \\
a_{21} + b_{21} & a_{22} + b_{22}
\end{pmatrix}
$$

In [7]:
C = np.ones((3,2))
C

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
A + C

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

## Produit matriciel

Soient les matrices $A$ de dimension $2 \times 2$ et $B$ de dimension $2 \times 3$ :
$$
A = \begin{pmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{pmatrix}, \quad
B = \begin{pmatrix}
b_{11} & b_{12} & b_{13} \\
b_{21} & b_{22} & b_{23}
\end{pmatrix}
$$

Le produit matriciel de $A$ et $B$, noté $AB$, est donné par :
$$
AB = \begin{pmatrix}
a_{11}b_{11} + a_{12}b_{21} & a_{11}b_{12} + a_{12}b_{22} & a_{11}b_{13} + a_{12}b_{23} \\
a_{21}b_{11} + a_{22}b_{21} & a_{21}b_{12} + a_{22}b_{22} & a_{21}b_{13} + a_{22}b_{23}
\end{pmatrix}
$$


In [12]:
# A.dot(C)
A.dot(B)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])