<a href="https://colab.research.google.com/github/be-next/TP-IA/blob/main/TP_IA_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Encoder

## Label Encoder



In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [2]:
y = np.array(['chat', 'chien', 'chat', 'oiseau'])

### création d'un encoder

In [3]:
encoder = LabelEncoder()
encoder.fit(y)

LabelEncoder()

In [5]:
encoder.classes_

array(['chat', 'chien', 'oiseau'], dtype='<U6')

### encodage des données

``transform``

In [6]:
encoder.transform(y)

array([0, 1, 0, 2])

### Décodage des données

``inverse_transform``

In [8]:
encoder.inverse_transform(np.array([0, 0, 2, 1]))

array(['chat', 'chat', 'oiseau', 'chien'], dtype='<U6')

## Ordinal Encoder

Permet d'encoder un tableau en plusieurs dimensions.


In [13]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
X = np.array([
  ['chat', 'poils'],
  ['chien', 'poils'],
  ['chat', 'poils'],
  ['oiseau', 'plumes']
])

In [14]:
encoder = OrdinalEncoder()
encoder.fit_transform(X)

array([[0., 1.],
       [1., 1.],
       [0., 1.],
       [2., 0.]])

### Point d'attention

Les valeurs résultants de la transformation doivent être comprises comme des classes d'objets représentées par un nombre. Cependant, certains modèles peuvent interpreter ces valeurs au travers d'une relation d'ordre, i.e. 'chat' < 'chien' < 'oiseau'...

Il existe le one hot encodeur qui represente les classes d'objets de manière binaire.

## One Hot Encoder

Autant de colonnes qu'il y a de classe dans la variable ==> les catégories sont distribuées sur autant de dimension.

In [15]:
from sklearn.preprocessing import LabelBinarizer

In [16]:
y

array(['chat', 'chien', 'chat', 'oiseau'], dtype='<U6')

In [19]:
encoder = LabelBinarizer() # sparse_output=True)
encoder.fit_transform(y)

array([[1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

### Point d'attention

Matrice creuse, format très léger, car le zéro n'est pas stocké.

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
X

array([['chat', 'poils'],
       ['chien', 'poils'],
       ['chat', 'poils'],
       ['oiseau', 'plumes']], dtype='<U6')

In [22]:
encoder = OneHotEncoder()
encoder.fit_transform(X) # matrice encodée CSR

<4x5 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>